### PR TITLE
LaTeX: add xelatexWithHeaders

### PR DESCRIPTION
**Pull request by Krantz-XRF**
Changes:

- Introduce `someTexWithHeaders`
- `latexWithHeaders` as a special case of `someTexWithHeaders`
- Introduce `xelatexWithHeaders`, as a special case of `someTexWithHeaders`
  - Remove use of package CTeX
- Introduce `ctexWithHeaders`, as a special case of `someTexWithHeaders`
- `latex` as a special case of `latexWithHeaders`
- `xelatex` as a special case of `xelatexWithHeaders`
  - Remove use of package CTeX
- Introduce `ctex`, as a special case of `ctexWithHeaders`
- Export `xelatexWithHeaders`, `ctex`, `ctexWithHeaders` in module `Reanimate.LaTeX`
- Export `ctex` in module `Reanimate`
- Change `xelatex` to `ctex` in `doc_xelatex.hs`

Breaking Changes:

- `xelatex` does not automatically use package CTeX now
- `ctex` has the old behavior of `xelatex` (with package CTeX)

### CODE REVIEW

**Comment by Lemmih** [comment]
Yeah, it sounds sensible to have a version of 'xelatex' without 'ctex'.

**Comment by Krantz-XRF** [comment]
I would propose to rename the current `xelatex` function to `ctex`, and make `xelatex` without `\usepackage{ctex}`, but I guess this will (silently) break some existing code.

**Comment by Lemmih** [comment]
Breaking changes are fine.

**Comment by Lemmih** [comment]
Could you rename `doc_xelatex.hs` to `doc_ctex.hs`. And could you add a new example for `xelatex`. The example could use unicode symbols instead of chinese symbols.

**Comment by Krantz-XRF** [comment]
I tried this for a `xelatex` example:
```haskell
main :: IO ()
main = reanimate $ docEnv $ animate $ const $
  withStrokeWidth 0 . withFillOpacity 1 . scale 4 . center $
  xelatex "αβγδε"
```

It seems that I don't have a proper font, it produces a GIF like this:
test

**Comment by Lemmih** [comment]
Hm, I can't come up with an example where `xelatex` differs from plain `latex`. Let's delete the `doc_xelatex.hs` example.

**Pull request merged**
