### PR TITLE
Fork() and Waitpid() Simulator

### PR DESCRIPTION
**Pull request by as0501**
## About
This is an animation to help beginner C programmers visualize the fork() and waitpid() system calls. It includes multiple types and functions that are helpful for creating animated line segments with text labels using Reanimate. If included in the examples folder, programmers may find my code useful for creating systems programming related teaching resources or more generally, animations with multiple line segments and text labels.

## Applications
This is one of the 6 animations created for the website: [fork-resource](https://as0501.github.io/fork-resource/).

### CODE REVIEW

**Comment by lemmih** [comment]
That's very cool. I have a few suggestions:

- Use `signalA (curveS 2)` to get smoother animations.
- Draw text with `withStrokeWidth 0` to get sharper text. Drawing text with `latex` with a non-zero stroke width tends to be less sharp.
- Use `& strokeLineCap .~ pure CapSquare` to make the lines meet up neatly.
- Use `oFadeIn` instead of `staticFrame` to make every line appear smoothly.

Here's a quick mockup (text should ideally be bigger):

https://user-images.githubusercontent.com/1443107/173179602-3e87b2cf-6282-40fd-833c-d691824d8d4c.mp4

**Comment by as0501** [comment]
Thank you so much for your feedback! I incorporated your changes but I had some trouble with using `withStrokeWidth 0`. I'm a Haskell Beginner (and a Reanimate Beginner) so please bear with me if my questions/confusion seems self-explanatory!

When I included `withStrokeWidth 0` in my `outlinedText` function, my white outline disappeared. When I added  `withStrokeWidth 0` to my `mkTextLabel` function, my text disappeared. So then, I changed the stroke width to a smaller value to make my text appear thinner and more similar to the animation that you created. I think I may have misunderstood what you meant by use `withStrokeWidth 0` since it hasn't given me the desired effect. I'd appreciate any feedback/advice you have.

Thank you so much for your time!

**Comment by lemmih** [comment]
You can change `center $ latex txt` to `withStrokeWidth 0 $ withFillOpacity 1 $ center $ latex txt`. Then the text will be filled rather than stroked.

**Comment by as0501** [comment]
That worked for me! 
Screen Shot 2022-06-11 at 9 05 19 PM

I appreciate all of your help and feedback. I look forward to hearing any other improvements you may have!

**Comment by lemmih** [comment]
Nice!

**Pull request merged**
