### PR TITLE
[WIP] - Adding haskell.nix based default and shell.nix

### PR DESCRIPTION
**Pull request by commandodev**
See also #140

### CODE REVIEW

**Comment by Lemmih** [comment]
Is there more to be done here or can I merge this PR?

**Comment by commandodev** [comment]
@Lemmih yep, I think this is good as is. Maybe a little section in the readme on how to use the nix integration would be useful?

**Comment by Lemmih** [comment]
Yeah, definitely.

**Comment by Lemmih** [comment]
Oh darn, nix doesn't like using stackage LTS-16.12?

**Comment by commandodev** [comment]
Looks like it might have bumped since this was last built? Should be an easy fix. I'll rebase and fix (but maybe later this afternoon)

**Pull request merged**
